stages:
  check_packages:
    cmd: python stages/check_packages.py --config=params.yaml
    always_changed: true
    outs:
      - ${base.pkg_list_fname}
  data_split: 
    cmd: python stages/data_split.py --config=params.yaml
    deps:
      - stages/data_split.py
      - ${base.pkg_list_fname}
      - ${base.data_dir}/${base.data_fname}
    params:
      - base
      - data_split
    outs:
      - data/X_train.pkl
      - data/X_test.pkl
      - data/y_train.pkl
      - data/y_test.pkl
  train:
    cmd: python stages/train.py --config=params.yaml
    deps:
      - stages/train.py
      - ${base.pkg_list_fname}
      - data/X_train.pkl
      - data/y_train.pkl
    params:
      - base
      - train
    outs:
      - ${train.models_dir}
  eval:
    cmd: python stages/eval.py --config=params.yaml
    deps:
      - stages/eval.py
      - ${base.pkg_list_fname}
      - data/X_test.pkl
      - data/y_test.pkl
    params:
      - base
      - data_split
      - train
      - eval
    outs:
      - ${eval.metrics_fpath}

