base:
  project: bank_customer_churn
  data_dir: data
  data_fname: Churn_Modelling.csv
  cat_cols: [Geography, Gender]
  num_cols: [CreditScore, Age, Tenure, Balance, NumOfProducts, HasCrCard, IsActiveMember,
    EstimatedSalary]
  targ_col: Exited
  random_state: 42

data_split:
  test_size: 0.2

train:
  models_dir: models
  model_fname: pipe.joblib
  n_estimators: 400
  num_leaves: 30
  learning_rate: 0.01
  max_depth: 30
  reg_alpha: 0.0
  reg_lambda: 0.0

eval:
  metrics_dir: metrics
  metrics_fname: metrics.json
  confusion_matrix_fname: cm.png
