base:
  project: bank_customer_churn
  data_dir: data
  data_fname: Churn_Modelling.csv
  cat_cols: ['Geography', 'Gender']
  num_cols: ['CreditScore', 'Age', 'Tenure', 
             'Balance', 'NumOfProducts', 'HasCrCard',
             'IsActiveMember', 'EstimatedSalary']
  targ_col: 'Exited'
  pkg_list_fname: pkg_list.txt
  random_state: 42

data_split:
  test_size: 0.25

train:
  models_dir: models
  model_fname: clf.joblib

eval:
  metrics_fpath: metrics.json