base:
  project: bank_customer_churn
  data_dir: data
  data_fname: Churn_Modelling.csv
  cat_cols:
  - Geography
  - Gender
  num_cols:
  - CreditScore
  - Age
  - Tenure
  - Balance
  - NumOfProducts
  - HasCrCard
  - IsActiveMember
  - EstimatedSalary
  targ_col: Exited
  random_state: 42
  model_dir: .mlem/model
  model_name: xgboost-model

data_split:
  test_size: 0.25

train:
  model_type: xgboost
  params:
    n_estimators: 200
    max_depth: 10

eval:
  perm_imp_model_path: models/perm_imp.joblib
