base:
  project: bank_customer_churn
  data_dir: data
  data_fname: Churn_Modelling.csv
  cat_cols: 
  - Geography
  - Gender
  num_cols:
  - CreditScore
  - Age
  - Tenure
  - Balance
  - NumOfProducts
  - HasCrCard
  - IsActiveMember
  - EstimatedSalary
  targ_col: Exited
  random_state: 42

data_split:
  test_size: 0.25

train:
  models_dir: models
  model_fname: model.joblib
  params:
    n_estimators: 50
    max_depth: 5
